#!/usr/bin/env node

var fs   = require('fs'),
    fse  = require('fs-extra'),
    path = require('path')


fs.readdirSync(path.resolve(__dirname, '../examples')).forEach(function(example) {
  var coreDir = path.resolve(__dirname, '..')
  var apiDir  = path.resolve(__dirname, '../node_modules/livereactload-api')

  console.log('symlink:', example)
  symlink(path.resolve(__dirname, '../examples', example, 'node_modules/livereactload'), coreDir)
  symlink(path.resolve(__dirname, '../examples', example, 'node_modules/livereactload-api'), apiDir)
})

function symlink(dest, src) {
  if (fs.existsSync(dest)) {
    fse.removeSync(dest)
    fs.symlinkSync(src, dest, 'dir')
  }
}
